<?php
/**
 * S2sSnapchatEventType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sedo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * platform-api
 *
 * # Introduction and Process Overview  This API helps manage content campaigns, reporting and other parts of Sedo Traffic Monetization Platform  *Note: Please note that the API is still in development and some endpoints may not be available yet.*  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\Platform\Model;
use \Sedo\ObjectSerializer;

/**
 * S2sSnapchatEventType Class Doc Comment
 *
 * @category Class
 * @description Following events are supported by Snapchat Conversion API and can be used for search, click, and landing page events.
 * @package  Sedo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class S2sSnapchatEventType
{
    /**
     * Possible values of this enum
     */
    public const PURCHASE = 'PURCHASE';

    public const SAVE = 'SAVE';

    public const START_CHECKOUT = 'START_CHECKOUT';

    public const ADD_CART = 'ADD_CART';

    public const VIEW_CONTENT = 'VIEW_CONTENT';

    public const ADD_BILLING = 'ADD_BILLING';

    public const SIGN_UP = 'SIGN_UP';

    public const SEARCH = 'SEARCH';

    public const PAGE_VIEW = 'PAGE_VIEW';

    public const SUBSCRIBE = 'SUBSCRIBE';

    public const AD_CLICK = 'AD_CLICK';

    public const AD_VIEW = 'AD_VIEW';

    public const COMPLETE_TUTORIAL = 'COMPLETE_TUTORIAL';

    public const LEVEL_COMPLETE = 'LEVEL_COMPLETE';

    public const INVITE = 'INVITE';

    public const LOGIN = 'LOGIN';

    public const SHARE = 'SHARE';

    public const RESERVE = 'RESERVE';

    public const ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED';

    public const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

    public const SPENT_CREDITS = 'SPENT_CREDITS';

    public const RATE = 'RATE';

    public const START_TRIAL = 'START_TRIAL';

    public const LIST_VIEW = 'LIST_VIEW';

    public const APP_INSTALL = 'APP_INSTALL';

    public const APP_OPEN = 'APP_OPEN';

    public const CUSTOM_EVENT_1 = 'CUSTOM_EVENT_1';

    public const CUSTOM_EVENT_2 = 'CUSTOM_EVENT_2';

    public const CUSTOM_EVENT_3 = 'CUSTOM_EVENT_3';

    public const CUSTOM_EVENT_4 = 'CUSTOM_EVENT_4';

    public const CUSTOM_EVENT_5 = 'CUSTOM_EVENT_5';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PURCHASE,
            self::SAVE,
            self::START_CHECKOUT,
            self::ADD_CART,
            self::VIEW_CONTENT,
            self::ADD_BILLING,
            self::SIGN_UP,
            self::SEARCH,
            self::PAGE_VIEW,
            self::SUBSCRIBE,
            self::AD_CLICK,
            self::AD_VIEW,
            self::COMPLETE_TUTORIAL,
            self::LEVEL_COMPLETE,
            self::INVITE,
            self::LOGIN,
            self::SHARE,
            self::RESERVE,
            self::ACHIEVEMENT_UNLOCKED,
            self::ADD_TO_WISHLIST,
            self::SPENT_CREDITS,
            self::RATE,
            self::START_TRIAL,
            self::LIST_VIEW,
            self::APP_INSTALL,
            self::APP_OPEN,
            self::CUSTOM_EVENT_1,
            self::CUSTOM_EVENT_2,
            self::CUSTOM_EVENT_3,
            self::CUSTOM_EVENT_4,
            self::CUSTOM_EVENT_5
        ];
    }
}


