<?php

/**
 * S2sXTrackingSettings.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * platform-api.
 *
 * # Introduction and Process Overview  This API helps manage content campaigns, reporting and other parts of Sedo Traffic Monetization Platform  *Note: Please note that the API is still in development and some endpoints may not be available yet.*  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\Platform\Model;

use Sedo\ObjectSerializer;

/**
 * S2sXTrackingSettings Class Doc Comment.
 *
 * @category Class
 *
 * @description Settings for tracking with Twitter (X)  traffic source.  For detailed guidance on setting up and using the pixel, please refer to the official documentation: [Twitter (X) Conversion API](https://developer.x.com/en/docs/x-ads-api/measurement/web-conversions/conversion-api).
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class S2sXTrackingSettings implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'S2sXTrackingSettings';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        's2sXPixelId' => 'string',
        's2sXLandingPageEvent' => 'string',
        's2sXSearchEvent' => 'string',
        's2sXClickEvent' => 'string',
        'type' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        's2sXPixelId' => null,
        's2sXLandingPageEvent' => null,
        's2sXSearchEvent' => null,
        's2sXClickEvent' => null,
        'type' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        's2sXPixelId' => false,
        's2sXLandingPageEvent' => false,
        's2sXSearchEvent' => false,
        's2sXClickEvent' => false,
        'type' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        's2sXPixelId' => 's2sXPixelId',
        's2sXLandingPageEvent' => 's2sXLandingPageEvent',
        's2sXSearchEvent' => 's2sXSearchEvent',
        's2sXClickEvent' => 's2sXClickEvent',
        'type' => 'type',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        's2sXPixelId' => 'setS2sXPixelId',
        's2sXLandingPageEvent' => 'setS2sXLandingPageEvent',
        's2sXSearchEvent' => 'setS2sXSearchEvent',
        's2sXClickEvent' => 'setS2sXClickEvent',
        'type' => 'setType',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        's2sXPixelId' => 'getS2sXPixelId',
        's2sXLandingPageEvent' => 'getS2sXLandingPageEvent',
        's2sXSearchEvent' => 'getS2sXSearchEvent',
        's2sXClickEvent' => 'getS2sXClickEvent',
        'type' => 'getType',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[]|null $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('s2sXPixelId', $data ?? [], null);
        $this->setIfExists('s2sXLandingPageEvent', $data ?? [], null);
        $this->setIfExists('s2sXSearchEvent', $data ?? [], null);
        $this->setIfExists('s2sXClickEvent', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['s2sXPixelId']) {
            $invalidProperties[] = "'s2sXPixelId' can't be null";
        }
        if (null === $this->container['type']) {
            $invalidProperties[] = "'type' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets s2sXPixelId.
     *
     * @return string
     */
    public function getS2sXPixelId()
    {
        return $this->container['s2sXPixelId'];
    }

    /**
     * Sets s2sXPixelId.
     *
     * @param string $s2sXPixelId This parameter represents the Event Pixel ID obtained from the Twitter (X) Events Manager. It is essential for tracking user interactions and conversions.  For detailed guidance on setting up and using the pixel, please refer to the official documentation: [Twitter (X) Conversion API](https://developer.x.com/en/docs/x-ads-api/measurement/web-conversions/conversion-api)
     *
     * @return self
     */
    public function setS2sXPixelId($s2sXPixelId)
    {
        if (is_null($s2sXPixelId)) {
            throw new \InvalidArgumentException('non-nullable s2sXPixelId cannot be null');
        }
        $this->container['s2sXPixelId'] = $s2sXPixelId;

        return $this;
    }

    /**
     * Gets s2sXLandingPageEvent.
     *
     * @return string|null
     */
    public function getS2sXLandingPageEvent()
    {
        return $this->container['s2sXLandingPageEvent'];
    }

    /**
     * Sets s2sXLandingPageEvent.
     *
     * @param string|null $s2sXLandingPageEvent event name for the Landing Visit event
     *
     * @return self
     */
    public function setS2sXLandingPageEvent($s2sXLandingPageEvent)
    {
        if (is_null($s2sXLandingPageEvent)) {
            throw new \InvalidArgumentException('non-nullable s2sXLandingPageEvent cannot be null');
        }
        $this->container['s2sXLandingPageEvent'] = $s2sXLandingPageEvent;

        return $this;
    }

    /**
     * Gets s2sXSearchEvent.
     *
     * @return string|null
     */
    public function getS2sXSearchEvent()
    {
        return $this->container['s2sXSearchEvent'];
    }

    /**
     * Sets s2sXSearchEvent.
     *
     * @param string|null $s2sXSearchEvent Event name for the Search event. Can be used for tracking \"1st\" click
     *
     * @return self
     */
    public function setS2sXSearchEvent($s2sXSearchEvent)
    {
        if (is_null($s2sXSearchEvent)) {
            throw new \InvalidArgumentException('non-nullable s2sXSearchEvent cannot be null');
        }
        $this->container['s2sXSearchEvent'] = $s2sXSearchEvent;

        return $this;
    }

    /**
     * Gets s2sXClickEvent.
     *
     * @return string|null
     */
    public function getS2sXClickEvent()
    {
        return $this->container['s2sXClickEvent'];
    }

    /**
     * Sets s2sXClickEvent.
     *
     * @param string|null $s2sXClickEvent Event name for the Ad Click or \"2nd\" click event. Commonly used for conversion tracking
     *
     * @return self
     */
    public function setS2sXClickEvent($s2sXClickEvent)
    {
        if (is_null($s2sXClickEvent)) {
            throw new \InvalidArgumentException('non-nullable s2sXClickEvent cannot be null');
        }
        $this->container['s2sXClickEvent'] = $s2sXClickEvent;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type.
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
