<?php

/**
 * PublishedArticleResponse.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * content-api.
 *
 * # Introduction and Process Overview  This API offers easy-to-use endpoints for managing articles on content sites using the Sedo Traffic Monetization Platform.  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\OpenApi\Content\Model;

use Sedo\SedoTMP\OpenApi\ObjectSerializer;

/**
 * PublishedArticleResponse Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class PublishedArticleResponse implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PublishedArticleResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'domain' => 'string',
        'url' => 'string',
        'slug' => 'string',
        'publishedId' => 'string',
        'articleId' => 'string',
        'publishedDate' => '\DateTime',
        'publishedStatus' => 'string',
        'publishedBy' => 'string',
        'title' => 'string',
        'excerpt' => 'string',
        'text' => 'string',
        'categoryId' => 'string',
        'tags' => 'string[]',
        'locale' => 'string',
        'createdDate' => '\DateTime',
        'lastModifiedDate' => '\DateTime',
        'partner' => 'string',
        'createdBy' => 'string',
        'lastModifiedBy' => 'string',
        'images' => '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleImage[]',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'uuid4',
        'domain' => null,
        'url' => null,
        'slug' => null,
        'publishedId' => 'uuid4',
        'articleId' => 'uuid4',
        'publishedDate' => 'date-time',
        'publishedStatus' => null,
        'publishedBy' => null,
        'title' => null,
        'excerpt' => null,
        'text' => null,
        'categoryId' => 'uuid4',
        'tags' => null,
        'locale' => 'bcp47',
        'createdDate' => 'date-time',
        'lastModifiedDate' => 'date-time',
        'partner' => null,
        'createdBy' => null,
        'lastModifiedBy' => null,
        'images' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'domain' => false,
        'url' => false,
        'slug' => false,
        'publishedId' => false,
        'articleId' => false,
        'publishedDate' => false,
        'publishedStatus' => false,
        'publishedBy' => false,
        'title' => false,
        'excerpt' => false,
        'text' => false,
        'categoryId' => false,
        'tags' => false,
        'locale' => false,
        'createdDate' => false,
        'lastModifiedDate' => false,
        'partner' => false,
        'createdBy' => false,
        'lastModifiedBy' => false,
        'images' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'domain' => 'domain',
        'url' => 'url',
        'slug' => 'slug',
        'publishedId' => 'publishedId',
        'articleId' => 'articleId',
        'publishedDate' => 'publishedDate',
        'publishedStatus' => 'publishedStatus',
        'publishedBy' => 'publishedBy',
        'title' => 'title',
        'excerpt' => 'excerpt',
        'text' => 'text',
        'categoryId' => 'categoryId',
        'tags' => 'tags',
        'locale' => 'locale',
        'createdDate' => 'createdDate',
        'lastModifiedDate' => 'lastModifiedDate',
        'partner' => 'partner',
        'createdBy' => 'createdBy',
        'lastModifiedBy' => 'lastModifiedBy',
        'images' => 'images',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'domain' => 'setDomain',
        'url' => 'setUrl',
        'slug' => 'setSlug',
        'publishedId' => 'setPublishedId',
        'articleId' => 'setArticleId',
        'publishedDate' => 'setPublishedDate',
        'publishedStatus' => 'setPublishedStatus',
        'publishedBy' => 'setPublishedBy',
        'title' => 'setTitle',
        'excerpt' => 'setExcerpt',
        'text' => 'setText',
        'categoryId' => 'setCategoryId',
        'tags' => 'setTags',
        'locale' => 'setLocale',
        'createdDate' => 'setCreatedDate',
        'lastModifiedDate' => 'setLastModifiedDate',
        'partner' => 'setPartner',
        'createdBy' => 'setCreatedBy',
        'lastModifiedBy' => 'setLastModifiedBy',
        'images' => 'setImages',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'domain' => 'getDomain',
        'url' => 'getUrl',
        'slug' => 'getSlug',
        'publishedId' => 'getPublishedId',
        'articleId' => 'getArticleId',
        'publishedDate' => 'getPublishedDate',
        'publishedStatus' => 'getPublishedStatus',
        'publishedBy' => 'getPublishedBy',
        'title' => 'getTitle',
        'excerpt' => 'getExcerpt',
        'text' => 'getText',
        'categoryId' => 'getCategoryId',
        'tags' => 'getTags',
        'locale' => 'getLocale',
        'createdDate' => 'getCreatedDate',
        'lastModifiedDate' => 'getLastModifiedDate',
        'partner' => 'getPartner',
        'createdBy' => 'getCreatedBy',
        'lastModifiedBy' => 'getLastModifiedBy',
        'images' => 'getImages',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PUBLISHED_STATUS_DRAFT = 'DRAFT';
    public const PUBLISHED_STATUS_PENDING = 'PENDING';
    public const PUBLISHED_STATUS_PUBLISHED = 'PUBLISHED';
    public const PUBLISHED_STATUS_ERROR = 'ERROR';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public function getPublishedStatusAllowableValues()
    {
        return [
            self::PUBLISHED_STATUS_DRAFT,
            self::PUBLISHED_STATUS_PENDING,
            self::PUBLISHED_STATUS_PUBLISHED,
            self::PUBLISHED_STATUS_ERROR,
        ];
    }

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[]|null $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('slug', $data ?? [], null);
        $this->setIfExists('publishedId', $data ?? [], null);
        $this->setIfExists('articleId', $data ?? [], null);
        $this->setIfExists('publishedDate', $data ?? [], null);
        $this->setIfExists('publishedStatus', $data ?? [], null);
        $this->setIfExists('publishedBy', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('excerpt', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('categoryId', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('createdDate', $data ?? [], null);
        $this->setIfExists('lastModifiedDate', $data ?? [], null);
        $this->setIfExists('partner', $data ?? [], null);
        $this->setIfExists('createdBy', $data ?? [], null);
        $this->setIfExists('lastModifiedBy', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPublishedStatusAllowableValues();
        if (!is_null($this->container['publishedStatus']) && !in_array($this->container['publishedStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'publishedStatus', must be one of '%s'",
                $this->container['publishedStatus'],
                implode("', '", $allowedValues)
            );
        }

        if (null === $this->container['title']) {
            $invalidProperties[] = "'title' can't be null";
        }
        if (null === $this->container['text']) {
            $invalidProperties[] = "'text' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id.
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets domain.
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain.
     *
     * @param string|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets url.
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url.
     *
     * @param string|null $url The published article url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets slug.
     *
     * @return string|null
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug.
     *
     * @param string|null $slug Slug of the published article
     *
     * @return self
     */
    public function setSlug($slug)
    {
        if (is_null($slug)) {
            throw new \InvalidArgumentException('non-nullable slug cannot be null');
        }
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets publishedId.
     *
     * @return string|null
     */
    public function getPublishedId()
    {
        return $this->container['publishedId'];
    }

    /**
     * Sets publishedId.
     *
     * @param string|null $publishedId publishedId
     *
     * @return self
     */
    public function setPublishedId($publishedId)
    {
        if (is_null($publishedId)) {
            throw new \InvalidArgumentException('non-nullable publishedId cannot be null');
        }
        $this->container['publishedId'] = $publishedId;

        return $this;
    }

    /**
     * Gets articleId.
     *
     * @return string|null
     */
    public function getArticleId()
    {
        return $this->container['articleId'];
    }

    /**
     * Sets articleId.
     *
     * @param string|null $articleId articleId
     *
     * @return self
     */
    public function setArticleId($articleId)
    {
        if (is_null($articleId)) {
            throw new \InvalidArgumentException('non-nullable articleId cannot be null');
        }
        $this->container['articleId'] = $articleId;

        return $this;
    }

    /**
     * Gets publishedDate.
     *
     * @return \DateTime|null
     */
    public function getPublishedDate()
    {
        return $this->container['publishedDate'];
    }

    /**
     * Sets publishedDate.
     *
     * @param \DateTime|null $publishedDate ISO-8601 formatted timestamp
     *
     * @return self
     */
    public function setPublishedDate($publishedDate)
    {
        if (is_null($publishedDate)) {
            throw new \InvalidArgumentException('non-nullable publishedDate cannot be null');
        }
        $this->container['publishedDate'] = $publishedDate;

        return $this;
    }

    /**
     * Gets publishedStatus.
     *
     * @return string|null
     */
    public function getPublishedStatus()
    {
        return $this->container['publishedStatus'];
    }

    /**
     * Sets publishedStatus.
     *
     * @param string|null $publishedStatus publishedStatus
     *
     * @return self
     */
    public function setPublishedStatus($publishedStatus)
    {
        if (is_null($publishedStatus)) {
            throw new \InvalidArgumentException('non-nullable publishedStatus cannot be null');
        }
        $allowedValues = $this->getPublishedStatusAllowableValues();
        if (!in_array($publishedStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(sprintf("Invalid value '%s' for 'publishedStatus', must be one of '%s'", $publishedStatus, implode("', '", $allowedValues)));
        }
        $this->container['publishedStatus'] = $publishedStatus;

        return $this;
    }

    /**
     * Gets publishedBy.
     *
     * @return string|null
     */
    public function getPublishedBy()
    {
        return $this->container['publishedBy'];
    }

    /**
     * Sets publishedBy.
     *
     * @param string|null $publishedBy Username of the user who operated on the resource
     *
     * @return self
     */
    public function setPublishedBy($publishedBy)
    {
        if (is_null($publishedBy)) {
            throw new \InvalidArgumentException('non-nullable publishedBy cannot be null');
        }
        $this->container['publishedBy'] = $publishedBy;

        return $this;
    }

    /**
     * Gets title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title.
     *
     * @param string $title Article title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets excerpt.
     *
     * @return string|null
     */
    public function getExcerpt()
    {
        return $this->container['excerpt'];
    }

    /**
     * Sets excerpt.
     *
     * @param string|null $excerpt Short excerpt of the text
     *
     * @return self
     */
    public function setExcerpt($excerpt)
    {
        if (is_null($excerpt)) {
            throw new \InvalidArgumentException('non-nullable excerpt cannot be null');
        }
        $this->container['excerpt'] = $excerpt;

        return $this;
    }

    /**
     * Gets text.
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text.
     *
     * @param string $text Full text content
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets categoryId.
     *
     * @return string|null
     */
    public function getCategoryId()
    {
        return $this->container['categoryId'];
    }

    /**
     * Sets categoryId.
     *
     * @param string|null $categoryId categoryId
     *
     * @return self
     */
    public function setCategoryId($categoryId)
    {
        if (is_null($categoryId)) {
            throw new \InvalidArgumentException('non-nullable categoryId cannot be null');
        }
        $this->container['categoryId'] = $categoryId;

        return $this;
    }

    /**
     * Gets tags.
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags.
     *
     * @param string[]|null $tags List of tags that describe the article. These tags help categorize articles and group similar articles together.  Note:   * Tags do not affect the ads displayed. They should not be confused with ad keywords.   * Multiple tags should be sent as an array, not as a single long string.
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets locale.
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale.
     *
     * @param string|null $locale Audience language (Language tag formatted)
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets createdDate.
     *
     * @return \DateTime|null
     */
    public function getCreatedDate()
    {
        return $this->container['createdDate'];
    }

    /**
     * Sets createdDate.
     *
     * @param \DateTime|null $createdDate ISO-8601 formatted timestamp
     *
     * @return self
     */
    public function setCreatedDate($createdDate)
    {
        if (is_null($createdDate)) {
            throw new \InvalidArgumentException('non-nullable createdDate cannot be null');
        }
        $this->container['createdDate'] = $createdDate;

        return $this;
    }

    /**
     * Gets lastModifiedDate.
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['lastModifiedDate'];
    }

    /**
     * Sets lastModifiedDate.
     *
     * @param \DateTime|null $lastModifiedDate ISO-8601 formatted timestamp
     *
     * @return self
     */
    public function setLastModifiedDate($lastModifiedDate)
    {
        if (is_null($lastModifiedDate)) {
            throw new \InvalidArgumentException('non-nullable lastModifiedDate cannot be null');
        }
        $this->container['lastModifiedDate'] = $lastModifiedDate;

        return $this;
    }

    /**
     * Gets partner.
     *
     * @return string|null
     */
    public function getPartner()
    {
        return $this->container['partner'];
    }

    /**
     * Sets partner.
     *
     * @param string|null $partner Partner to assigned to the resource. Requires corresponding privileges
     *
     * @return self
     */
    public function setPartner($partner)
    {
        if (is_null($partner)) {
            throw new \InvalidArgumentException('non-nullable partner cannot be null');
        }
        $this->container['partner'] = $partner;

        return $this;
    }

    /**
     * Gets createdBy.
     *
     * @return string|null
     */
    public function getCreatedBy()
    {
        return $this->container['createdBy'];
    }

    /**
     * Sets createdBy.
     *
     * @param string|null $createdBy Username of the user who operated on the resource
     *
     * @return self
     */
    public function setCreatedBy($createdBy)
    {
        if (is_null($createdBy)) {
            throw new \InvalidArgumentException('non-nullable createdBy cannot be null');
        }
        $this->container['createdBy'] = $createdBy;

        return $this;
    }

    /**
     * Gets lastModifiedBy.
     *
     * @return string|null
     */
    public function getLastModifiedBy()
    {
        return $this->container['lastModifiedBy'];
    }

    /**
     * Sets lastModifiedBy.
     *
     * @param string|null $lastModifiedBy Username of the user who operated on the resource
     *
     * @return self
     */
    public function setLastModifiedBy($lastModifiedBy)
    {
        if (is_null($lastModifiedBy)) {
            throw new \InvalidArgumentException('non-nullable lastModifiedBy cannot be null');
        }
        $this->container['lastModifiedBy'] = $lastModifiedBy;

        return $this;
    }

    /**
     * Gets images.
     *
     * @return ArticleImage[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images.
     *
     * @param ArticleImage[]|null $images images
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
