<?php
/**
 * Platform
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Sedo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * content-api
 *
 * # Introduction and Process Overview  This API offers easy-to-use endpoints for managing articles on content sites using the Sedo Traffic Monetization Platform.  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\Content\Model;
use \Sedo\ObjectSerializer;

/**
 * Platform Class Doc Comment
 *
 * @category Class
 * @description Content site API platform
 * @package  Sedo
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Platform
{
    /**
     * Possible values of this enum
     */
    public const WORDPRESS = 'WORDPRESS';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WORDPRESS
        ];
    }
}


