<?php

/**
 * ArticleApi
 * PHP version 8.1.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * content-api.
 *
 * # Introduction and Process Overview  This API offers easy-to-use endpoints for managing articles on content sites using the Sedo Traffic Monetization Platform.  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\OpenApi\Content\API;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Sedo\SedoTMP\OpenApi\ApiException;
use Sedo\SedoTMP\OpenApi\Configuration;
use Sedo\SedoTMP\OpenApi\HeaderSelector;
use Sedo\SedoTMP\OpenApi\ObjectSerializer;

/**
 * ArticleApi Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
class ArticleApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] * */
    public const contentTypes = [
        'articlesGet' => [
            'application/json',
        ],
        'articlesIdDelete' => [
            'application/json',
        ],
        'articlesIdGet' => [
            'application/json',
        ],
        'articlesIdPatch' => [
            'application/json',
        ],
        'articlesIdPut' => [
            'application/json',
        ],
        'articlesPost' => [
            'application/json',
        ],
    ];

    /**
     * @param int $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0,
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index.
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index.
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation articlesGet.
     *
     * Retrieve a list of articles
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\Pageable|null $page        Pageable object (every key is a separate query parameter) (optional)
     * @param string|null                                       $term        Search term for matching against any text field e.g. ID, title, excerpt, text.. (optional)
     * @param string                                            $contentType The value for the Content-Type header. Check self::contentTypes['articlesGet'] to see the possible values for this operation
     *
     * @return \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse[]|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesGet($page = null, $term = null, string $contentType = self::contentTypes['articlesGet'][0])
    {
        list($response) = $this->articlesGetWithHttpInfo($page, $term, $contentType);

        return $response;
    }

    /**
     * Operation articlesGetWithHttpInfo.
     *
     * Retrieve a list of articles
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\Pageable|null $page        Pageable object (every key is a separate query parameter) (optional)
     * @param string|null                                       $term        Search term for matching against any text field e.g. ID, title, excerpt, text.. (optional)
     * @param string                                            $contentType The value for the Content-Type header. Check self::contentTypes['articlesGet'] to see the possible values for this operation
     *
     * @return array of \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse[]|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesGetWithHttpInfo($page = null, $term = null, string $contentType = self::contentTypes['articlesGet'][0])
    {
        $request = $this->articlesGetRequest($page, $term, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }

            return $this->handleResponseWithDataType(
                '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation articlesGetAsync.
     *
     * Retrieve a list of articles
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\Pageable|null $page        Pageable object (every key is a separate query parameter) (optional)
     * @param string|null                                       $term        Search term for matching against any text field e.g. ID, title, excerpt, text.. (optional)
     * @param string                                            $contentType The value for the Content-Type header. Check self::contentTypes['articlesGet'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesGetAsync($page = null, $term = null, string $contentType = self::contentTypes['articlesGet'][0])
    {
        return $this->articlesGetAsyncWithHttpInfo($page, $term, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation articlesGetAsyncWithHttpInfo.
     *
     * Retrieve a list of articles
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\Pageable|null $page        Pageable object (every key is a separate query parameter) (optional)
     * @param string|null                                       $term        Search term for matching against any text field e.g. ID, title, excerpt, text.. (optional)
     * @param string                                            $contentType The value for the Content-Type header. Check self::contentTypes['articlesGet'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesGetAsyncWithHttpInfo($page = null, $term = null, string $contentType = self::contentTypes['articlesGet'][0])
    {
        $returnType = '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse[]';
        $request = $this->articlesGetRequest($page, $term, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'articlesGet'.
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\Pageable|null $page        Pageable object (every key is a separate query parameter) (optional)
     * @param string|null                                       $term        Search term for matching against any text field e.g. ID, title, excerpt, text.. (optional)
     * @param string                                            $contentType The value for the Content-Type header. Check self::contentTypes['articlesGet'] to see the possible values for this operation
     *
     * @return Request
     *
     * @throws \InvalidArgumentException
     */
    public function articlesGetRequest($page = null, $term = null, string $contentType = self::contentTypes['articlesGet'][0])
    {
        $resourcePath = '/articles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'object', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $term,
            'term', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer '.$this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation articlesIdDelete.
     *
     * Delete an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdDelete'] to see the possible values for this operation
     *
     * @return void
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdDelete($id, string $contentType = self::contentTypes['articlesIdDelete'][0])
    {
        $this->articlesIdDeleteWithHttpInfo($id, $contentType);
    }

    /**
     * Operation articlesIdDeleteWithHttpInfo.
     *
     * Delete an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdDelete'] to see the possible values for this operation
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdDeleteWithHttpInfo($id, string $contentType = self::contentTypes['articlesIdDelete'][0])
    {
        $request = $this->articlesIdDeleteRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }

            $statusCode = $response->getStatusCode();

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation articlesIdDeleteAsync.
     *
     * Delete an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdDelete'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdDeleteAsync($id, string $contentType = self::contentTypes['articlesIdDelete'][0])
    {
        return $this->articlesIdDeleteAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation articlesIdDeleteAsyncWithHttpInfo.
     *
     * Delete an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdDelete'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdDeleteAsyncWithHttpInfo($id, string $contentType = self::contentTypes['articlesIdDelete'][0])
    {
        $returnType = '';
        $request = $this->articlesIdDeleteRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'articlesIdDelete'.
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdDelete'] to see the possible values for this operation
     *
     * @return Request
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdDeleteRequest($id, string $contentType = self::contentTypes['articlesIdDelete'][0])
    {
        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling articlesIdDelete');
        }

        $resourcePath = '/articles/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer '.$this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'DELETE',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation articlesIdGet.
     *
     * Retrieve an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdGet'] to see the possible values for this operation
     *
     * @return \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdGet($id, string $contentType = self::contentTypes['articlesIdGet'][0])
    {
        list($response) = $this->articlesIdGetWithHttpInfo($id, $contentType);

        return $response;
    }

    /**
     * Operation articlesIdGetWithHttpInfo.
     *
     * Retrieve an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdGet'] to see the possible values for this operation
     *
     * @return array of \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdGetWithHttpInfo($id, string $contentType = self::contentTypes['articlesIdGet'][0])
    {
        $request = $this->articlesIdGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }

            return $this->handleResponseWithDataType(
                '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation articlesIdGetAsync.
     *
     * Retrieve an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdGet'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdGetAsync($id, string $contentType = self::contentTypes['articlesIdGet'][0])
    {
        return $this->articlesIdGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation articlesIdGetAsyncWithHttpInfo.
     *
     * Retrieve an article by its ID
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdGet'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdGetAsyncWithHttpInfo($id, string $contentType = self::contentTypes['articlesIdGet'][0])
    {
        $returnType = '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse';
        $request = $this->articlesIdGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'articlesIdGet'.
     *
     * @param string $id          Resource id (required)
     * @param string $contentType The value for the Content-Type header. Check self::contentTypes['articlesIdGet'] to see the possible values for this operation
     *
     * @return Request
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdGetRequest($id, string $contentType = self::contentTypes['articlesIdGet'][0])
    {
        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling articlesIdGet');
        }

        $resourcePath = '/articles/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer '.$this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation articlesIdPatch.
     *
     * Partially update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPatch'] to see the possible values for this operation
     *
     * @return \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdPatch($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPatch'][0])
    {
        list($response) = $this->articlesIdPatchWithHttpInfo($id, $updateArticle, $contentType);

        return $response;
    }

    /**
     * Operation articlesIdPatchWithHttpInfo.
     *
     * Partially update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPatch'] to see the possible values for this operation
     *
     * @return array of \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdPatchWithHttpInfo($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPatch'][0])
    {
        $request = $this->articlesIdPatchRequest($id, $updateArticle, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }

            return $this->handleResponseWithDataType(
                '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation articlesIdPatchAsync.
     *
     * Partially update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPatch'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdPatchAsync($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPatch'][0])
    {
        return $this->articlesIdPatchAsyncWithHttpInfo($id, $updateArticle, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation articlesIdPatchAsyncWithHttpInfo.
     *
     * Partially update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPatch'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdPatchAsyncWithHttpInfo($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPatch'][0])
    {
        $returnType = '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse';
        $request = $this->articlesIdPatchRequest($id, $updateArticle, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'articlesIdPatch'.
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPatch'] to see the possible values for this operation
     *
     * @return Request
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdPatchRequest($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPatch'][0])
    {
        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling articlesIdPatch');
        }

        // verify the required parameter 'updateArticle' is set
        if (null === $updateArticle || (is_array($updateArticle) && 0 === count($updateArticle))) {
            throw new \InvalidArgumentException('Missing the required parameter $updateArticle when calling articlesIdPatch');
        }

        $resourcePath = '/articles/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateArticle)) {
            if (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($updateArticle));
            } else {
                $httpBody = $updateArticle;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer '.$this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'PATCH',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation articlesIdPut.
     *
     * Fully update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPut'] to see the possible values for this operation
     *
     * @return \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdPut($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPut'][0])
    {
        list($response) = $this->articlesIdPutWithHttpInfo($id, $updateArticle, $contentType);

        return $response;
    }

    /**
     * Operation articlesIdPutWithHttpInfo.
     *
     * Fully update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPut'] to see the possible values for this operation
     *
     * @return array of \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesIdPutWithHttpInfo($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPut'][0])
    {
        $request = $this->articlesIdPutRequest($id, $updateArticle, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }

            return $this->handleResponseWithDataType(
                '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation articlesIdPutAsync.
     *
     * Fully update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPut'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdPutAsync($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPut'][0])
    {
        return $this->articlesIdPutAsyncWithHttpInfo($id, $updateArticle, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation articlesIdPutAsyncWithHttpInfo.
     *
     * Fully update an article by its ID
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPut'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdPutAsyncWithHttpInfo($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPut'][0])
    {
        $returnType = '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse';
        $request = $this->articlesIdPutRequest($id, $updateArticle, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'articlesIdPut'.
     *
     * @param string                                            $id            Resource id (required)
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\UpdateArticle $updateArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesIdPut'] to see the possible values for this operation
     *
     * @return Request
     *
     * @throws \InvalidArgumentException
     */
    public function articlesIdPutRequest($id, $updateArticle, string $contentType = self::contentTypes['articlesIdPut'][0])
    {
        // verify the required parameter 'id' is set
        if (null === $id || (is_array($id) && 0 === count($id))) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling articlesIdPut');
        }

        // verify the required parameter 'updateArticle' is set
        if (null === $updateArticle || (is_array($updateArticle) && 0 === count($updateArticle))) {
            throw new \InvalidArgumentException('Missing the required parameter $updateArticle when calling articlesIdPut');
        }

        $resourcePath = '/articles/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if (null !== $id) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($updateArticle)) {
            if (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($updateArticle));
            } else {
                $httpBody = $updateArticle;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer '.$this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'PUT',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation articlesPost.
     *
     * Create a new article
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\CreateArticle $createArticle createArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesPost'] to see the possible values for this operation
     *
     * @return \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesPost($createArticle, string $contentType = self::contentTypes['articlesPost'][0])
    {
        list($response) = $this->articlesPostWithHttpInfo($createArticle, $contentType);

        return $response;
    }

    /**
     * Operation articlesPostWithHttpInfo.
     *
     * Create a new article
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\CreateArticle $createArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesPost'] to see the possible values for this operation
     *
     * @return array of \Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse|\Sedo\SedoTMP\OpenApi\Content\Model\Problem|\Sedo\SedoTMP\OpenApi\Content\Model\Problem, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws ApiException              on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     */
    public function articlesPostWithHttpInfo($createArticle, string $contentType = self::contentTypes['articlesPost'][0])
    {
        $request = $this->articlesPostRequest($createArticle, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $request,
                        $response,
                    );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }

            return $this->handleResponseWithDataType(
                '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\OpenApi\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation articlesPostAsync.
     *
     * Create a new article
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\CreateArticle $createArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesPost'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesPostAsync($createArticle, string $contentType = self::contentTypes['articlesPost'][0])
    {
        return $this->articlesPostAsyncWithHttpInfo($createArticle, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation articlesPostAsyncWithHttpInfo.
     *
     * Create a new article
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\CreateArticle $createArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesPost'] to see the possible values for this operation
     *
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function articlesPostAsyncWithHttpInfo($createArticle, string $contentType = self::contentTypes['articlesPost'][0])
    {
        $returnType = '\Sedo\SedoTMP\OpenApi\Content\Model\ArticleResponse';
        $request = $this->articlesPostRequest($createArticle, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== $returnType) {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
                }
            );
    }

    /**
     * Create request for operation 'articlesPost'.
     *
     * @param \Sedo\SedoTMP\OpenApi\Content\Model\CreateArticle $createArticle (required)
     * @param string                                            $contentType   The value for the Content-Type header. Check self::contentTypes['articlesPost'] to see the possible values for this operation
     *
     * @return Request
     *
     * @throws \InvalidArgumentException
     */
    public function articlesPostRequest($createArticle, string $contentType = self::contentTypes['articlesPost'][0])
    {
        // verify the required parameter 'createArticle' is set
        if (null === $createArticle || (is_array($createArticle) && 0 === count($createArticle))) {
            throw new \InvalidArgumentException('Missing the required parameter $createArticle when calling articlesPost');
        }

        $resourcePath = '/articles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createArticle)) {
            if (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createArticle));
            } else {
                $httpBody = $createArticle;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (false !== stripos($headers['Content-Type'], 'application/json')) {
                // if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer '.$this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost.$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option.
     *
     * @return array of http client options
     *
     * @throws \RuntimeException on file opening failure
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: '.$this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if ('\SplFileObject' === $dataType) {
            $content = $response->getBody(); // stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ('string' !== $dataType) {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(sprintf('Error JSON decoding server response (%s)', $request->getUri()), $response->getStatusCode(), $response->getHeaders(), $content);
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
