<?php

/**
 * PixelMetaTrackingSettings.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * platform-api.
 *
 * # Introduction and Process Overview  This API helps manage content campaigns, reporting and other parts of Sedo Traffic Monetization Platform  *Note: Please note that the API is still in development and some endpoints may not be available yet.*  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\OpenApi\Platform\Model;

use Sedo\SedoTMP\OpenApi\ObjectSerializer;

/**
 * PixelMetaTrackingSettings Class Doc Comment.
 *
 * @category Class
 *
 * @description Settings for pixel tracking with Meta traffic source  More details on how to set up the tracking can be found in the [Meta conversion tracking API documentation](https://developers.facebook.com/docs/marketing-api/conversions-api/get-started/)
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class PixelMetaTrackingSettings implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PixelMetaTrackingSettings';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'pixelMetaPixelId' => 'string',
        'pixelMetaLandingPageEvent' => 'string',
        'pixelMetaClickEvent' => 'string',
        'pixelMetaSearchEvent' => 'string',
        'type' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'pixelMetaPixelId' => null,
        'pixelMetaLandingPageEvent' => null,
        'pixelMetaClickEvent' => null,
        'pixelMetaSearchEvent' => null,
        'type' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'pixelMetaPixelId' => false,
        'pixelMetaLandingPageEvent' => false,
        'pixelMetaClickEvent' => false,
        'pixelMetaSearchEvent' => false,
        'type' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pixelMetaPixelId' => 'pixelMetaPixelId',
        'pixelMetaLandingPageEvent' => 'pixelMetaLandingPageEvent',
        'pixelMetaClickEvent' => 'pixelMetaClickEvent',
        'pixelMetaSearchEvent' => 'pixelMetaSearchEvent',
        'type' => 'type',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'pixelMetaPixelId' => 'setPixelMetaPixelId',
        'pixelMetaLandingPageEvent' => 'setPixelMetaLandingPageEvent',
        'pixelMetaClickEvent' => 'setPixelMetaClickEvent',
        'pixelMetaSearchEvent' => 'setPixelMetaSearchEvent',
        'type' => 'setType',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'pixelMetaPixelId' => 'getPixelMetaPixelId',
        'pixelMetaLandingPageEvent' => 'getPixelMetaLandingPageEvent',
        'pixelMetaClickEvent' => 'getPixelMetaClickEvent',
        'pixelMetaSearchEvent' => 'getPixelMetaSearchEvent',
        'type' => 'getType',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param mixed[]|null $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('pixelMetaPixelId', $data ?? [], null);
        $this->setIfExists('pixelMetaLandingPageEvent', $data ?? [], null);
        $this->setIfExists('pixelMetaClickEvent', $data ?? [], null);
        $this->setIfExists('pixelMetaSearchEvent', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['pixelMetaPixelId']) {
            $invalidProperties[] = "'pixelMetaPixelId' can't be null";
        }
        if (mb_strlen($this->container['pixelMetaPixelId']) < 1) {
            $invalidProperties[] = "invalid value for 'pixelMetaPixelId', the character length must be bigger than or equal to 1.";
        }

        if (null === $this->container['type']) {
            $invalidProperties[] = "'type' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets pixelMetaPixelId.
     *
     * @return string
     */
    public function getPixelMetaPixelId()
    {
        return $this->container['pixelMetaPixelId'];
    }

    /**
     * Sets pixelMetaPixelId.
     *
     * @param string $pixelMetaPixelId Pixel ID from Meta Events Manager. See for more details: https://www.facebook.com/business/help/952192354843755?id=1205376682832142  More details on how to set up the tracking can be found in the [Meta conversion tracking API documentation](https://developers.facebook.com/docs/marketing-api/conversions-api/get-started/)
     *
     * @return self
     */
    public function setPixelMetaPixelId($pixelMetaPixelId)
    {
        if (is_null($pixelMetaPixelId)) {
            throw new \InvalidArgumentException('non-nullable pixelMetaPixelId cannot be null');
        }

        if (mb_strlen($pixelMetaPixelId) < 1) {
            throw new \InvalidArgumentException('invalid length for $pixelMetaPixelId when calling PixelMetaTrackingSettings., must be bigger than or equal to 1.');
        }

        $this->container['pixelMetaPixelId'] = $pixelMetaPixelId;

        return $this;
    }

    /**
     * Gets pixelMetaLandingPageEvent.
     *
     * @return string|null
     */
    public function getPixelMetaLandingPageEvent()
    {
        return $this->container['pixelMetaLandingPageEvent'];
    }

    /**
     * Sets pixelMetaLandingPageEvent.
     *
     * @param string|null $pixelMetaLandingPageEvent Event name for the Landing Visit event
     *
     * @return self
     */
    public function setPixelMetaLandingPageEvent($pixelMetaLandingPageEvent)
    {
        if (is_null($pixelMetaLandingPageEvent)) {
            throw new \InvalidArgumentException('non-nullable pixelMetaLandingPageEvent cannot be null');
        }
        $this->container['pixelMetaLandingPageEvent'] = $pixelMetaLandingPageEvent;

        return $this;
    }

    /**
     * Gets pixelMetaClickEvent.
     *
     * @return string|null
     */
    public function getPixelMetaClickEvent()
    {
        return $this->container['pixelMetaClickEvent'];
    }

    /**
     * Sets pixelMetaClickEvent.
     *
     * @param string|null $pixelMetaClickEvent Event name for the Ad Click or \"2nd\" click event. Commonly used for conversion tracking
     *
     * @return self
     */
    public function setPixelMetaClickEvent($pixelMetaClickEvent)
    {
        if (is_null($pixelMetaClickEvent)) {
            throw new \InvalidArgumentException('non-nullable pixelMetaClickEvent cannot be null');
        }
        $this->container['pixelMetaClickEvent'] = $pixelMetaClickEvent;

        return $this;
    }

    /**
     * Gets pixelMetaSearchEvent.
     *
     * @return string|null
     */
    public function getPixelMetaSearchEvent()
    {
        return $this->container['pixelMetaSearchEvent'];
    }

    /**
     * Sets pixelMetaSearchEvent.
     *
     * @param string|null $pixelMetaSearchEvent Event name for the Search event. Can be used for tracking \"1st\" click
     *
     * @return self
     */
    public function setPixelMetaSearchEvent($pixelMetaSearchEvent)
    {
        if (is_null($pixelMetaSearchEvent)) {
            throw new \InvalidArgumentException('non-nullable pixelMetaSearchEvent cannot be null');
        }
        $this->container['pixelMetaSearchEvent'] = $pixelMetaSearchEvent;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type.
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
