<?php
/**
 * GeneratedArticleApi
 * PHP version 5
 *
 * @category Class
 * @package  Sedo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * content-api
 *
 * # Introduction and Process Overview  This API offers easy-to-use endpoints for managing articles on content sites using the Sedo Traffic Monetization Platform.  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\Content\API;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Sedo\ApiException;
use Sedo\Configuration;
use Sedo\HeaderSelector;
use Sedo\ObjectSerializer;

/**
 * GeneratedArticleApi Class Doc Comment
 *
 * @category Class
 * @package  Sedo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GeneratedArticleApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation generatedArticlesPost
     *
     * Generate a new article for a specified topic
     *
     * @param  \Sedo\SedoTMP\Content\Model\GenerateArticle $body body (required)
     * @param  \Sedo\SedoTMP\Content\Model\RequestFlowHeader $xSedoRequestFlow xSedoRequestFlow (optional)
     * @param  \Sedo\SedoTMP\Content\Model\ReferenceIdHeader $xSedoReferenceId xSedoReferenceId (optional)
     *
     * @throws \Sedo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Sedo\SedoTMP\Content\Model\ArticleResponse
     */
    public function generatedArticlesPost($body, $xSedoRequestFlow = null, $xSedoReferenceId = null)
    {
        list($response) = $this->generatedArticlesPostWithHttpInfo($body, $xSedoRequestFlow, $xSedoReferenceId);
        return $response;
    }

    /**
     * Operation generatedArticlesPostWithHttpInfo
     *
     * Generate a new article for a specified topic
     *
     * @param  \Sedo\SedoTMP\Content\Model\GenerateArticle $body (required)
     * @param  \Sedo\SedoTMP\Content\Model\RequestFlowHeader $xSedoRequestFlow (optional)
     * @param  \Sedo\SedoTMP\Content\Model\ReferenceIdHeader $xSedoReferenceId (optional)
     *
     * @throws \Sedo\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Sedo\SedoTMP\Content\Model\ArticleResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function generatedArticlesPostWithHttpInfo($body, $xSedoRequestFlow = null, $xSedoReferenceId = null)
    {
        $returnType = '\Sedo\SedoTMP\Content\Model\ArticleResponse';
        $request = $this->generatedArticlesPostRequest($body, $xSedoRequestFlow, $xSedoReferenceId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\Content\Model\ArticleResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Sedo\SedoTMP\Content\Model\Problem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation generatedArticlesPostAsync
     *
     * Generate a new article for a specified topic
     *
     * @param  \Sedo\SedoTMP\Content\Model\GenerateArticle $body (required)
     * @param  \Sedo\SedoTMP\Content\Model\RequestFlowHeader $xSedoRequestFlow (optional)
     * @param  \Sedo\SedoTMP\Content\Model\ReferenceIdHeader $xSedoReferenceId (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function generatedArticlesPostAsync($body, $xSedoRequestFlow = null, $xSedoReferenceId = null)
    {
        return $this->generatedArticlesPostAsyncWithHttpInfo($body, $xSedoRequestFlow, $xSedoReferenceId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation generatedArticlesPostAsyncWithHttpInfo
     *
     * Generate a new article for a specified topic
     *
     * @param  \Sedo\SedoTMP\Content\Model\GenerateArticle $body (required)
     * @param  \Sedo\SedoTMP\Content\Model\RequestFlowHeader $xSedoRequestFlow (optional)
     * @param  \Sedo\SedoTMP\Content\Model\ReferenceIdHeader $xSedoReferenceId (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function generatedArticlesPostAsyncWithHttpInfo($body, $xSedoRequestFlow = null, $xSedoReferenceId = null)
    {
        $returnType = '\Sedo\SedoTMP\Content\Model\ArticleResponse';
        $request = $this->generatedArticlesPostRequest($body, $xSedoRequestFlow, $xSedoReferenceId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'generatedArticlesPost'
     *
     * @param  \Sedo\SedoTMP\Content\Model\GenerateArticle $body (required)
     * @param  \Sedo\SedoTMP\Content\Model\RequestFlowHeader $xSedoRequestFlow (optional)
     * @param  \Sedo\SedoTMP\Content\Model\ReferenceIdHeader $xSedoReferenceId (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function generatedArticlesPostRequest($body, $xSedoRequestFlow = null, $xSedoReferenceId = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling generatedArticlesPost'
            );
        }

        $resourcePath = '/generated-articles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // header params
        if ($xSedoRequestFlow !== null) {
            $headerParams['X-Sedo-Request-Flow'] = ObjectSerializer::toHeaderValue($xSedoRequestFlow);
        }
        // header params
        if ($xSedoReferenceId !== null) {
            $headerParams['X-Sedo-Reference-Id'] = ObjectSerializer::toHeaderValue($xSedoReferenceId);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

            // // this endpoint requires Bearer token
            if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
            }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
