<?php
/**
 * PublishedArticleResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Sedo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * content-api
 *
 * # Introduction and Process Overview  This API offers easy-to-use endpoints for managing articles on content sites using the Sedo Traffic Monetization Platform.  # Authentication The API uses a modern OAuth authentication process to ensure security without sacrificing simplicity. To access the API, you need an access token. For more details on authentication, please refer to the [Introduction](/cms/docs-api/introduction) section.  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Sedo\SedoTMP\Content\Model;

use \ArrayAccess;
use \Sedo\ObjectSerializer;

/**
 * PublishedArticleResponse Class Doc Comment
 *
 * @category Class
 * @package  Sedo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublishedArticleResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PublishedArticleResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => '\Sedo\SedoTMP\Content\Model\Id',
        'domain' => 'string',
        'url' => 'string',
        'slug' => 'string',
        'publishedId' => '\Sedo\SedoTMP\Content\Model\Id',
        'articleId' => '\Sedo\SedoTMP\Content\Model\Id',
        'publishedDate' => '\Sedo\SedoTMP\Content\Model\\DateTime',
        'publishedStatus' => 'string',
        'publishedBy' => '\Sedo\SedoTMP\Content\Model\User',
        'title' => '\Sedo\SedoTMP\Content\Model\ArticleTitle',
        'excerpt' => '\Sedo\SedoTMP\Content\Model\ArticleExcerpt',
        'text' => '\Sedo\SedoTMP\Content\Model\ArticleText',
        'categoryId' => '\Sedo\SedoTMP\Content\Model\Id',
        'tags' => '\Sedo\SedoTMP\Content\Model\ArticleTags',
        'locale' => '\Sedo\SedoTMP\Content\Model\Locale',
        'createdDate' => '\Sedo\SedoTMP\Content\Model\\DateTime',
        'lastModifiedDate' => '\Sedo\SedoTMP\Content\Model\\DateTime',
        'partner' => '\Sedo\SedoTMP\Content\Model\Partner',
        'createdBy' => '\Sedo\SedoTMP\Content\Model\User',
        'lastModifiedBy' => '\Sedo\SedoTMP\Content\Model\User',
        'images' => '\Sedo\SedoTMP\Content\Model\ArticleImagesList'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'domain' => null,
        'url' => null,
        'slug' => null,
        'publishedId' => null,
        'articleId' => null,
        'publishedDate' => null,
        'publishedStatus' => null,
        'publishedBy' => null,
        'title' => null,
        'excerpt' => null,
        'text' => null,
        'categoryId' => null,
        'tags' => null,
        'locale' => null,
        'createdDate' => null,
        'lastModifiedDate' => null,
        'partner' => null,
        'createdBy' => null,
        'lastModifiedBy' => null,
        'images' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'domain' => 'domain',
        'url' => 'url',
        'slug' => 'slug',
        'publishedId' => 'publishedId',
        'articleId' => 'articleId',
        'publishedDate' => 'publishedDate',
        'publishedStatus' => 'publishedStatus',
        'publishedBy' => 'publishedBy',
        'title' => 'title',
        'excerpt' => 'excerpt',
        'text' => 'text',
        'categoryId' => 'categoryId',
        'tags' => 'tags',
        'locale' => 'locale',
        'createdDate' => 'createdDate',
        'lastModifiedDate' => 'lastModifiedDate',
        'partner' => 'partner',
        'createdBy' => 'createdBy',
        'lastModifiedBy' => 'lastModifiedBy',
        'images' => 'images'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'domain' => 'setDomain',
        'url' => 'setUrl',
        'slug' => 'setSlug',
        'publishedId' => 'setPublishedId',
        'articleId' => 'setArticleId',
        'publishedDate' => 'setPublishedDate',
        'publishedStatus' => 'setPublishedStatus',
        'publishedBy' => 'setPublishedBy',
        'title' => 'setTitle',
        'excerpt' => 'setExcerpt',
        'text' => 'setText',
        'categoryId' => 'setCategoryId',
        'tags' => 'setTags',
        'locale' => 'setLocale',
        'createdDate' => 'setCreatedDate',
        'lastModifiedDate' => 'setLastModifiedDate',
        'partner' => 'setPartner',
        'createdBy' => 'setCreatedBy',
        'lastModifiedBy' => 'setLastModifiedBy',
        'images' => 'setImages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'domain' => 'getDomain',
        'url' => 'getUrl',
        'slug' => 'getSlug',
        'publishedId' => 'getPublishedId',
        'articleId' => 'getArticleId',
        'publishedDate' => 'getPublishedDate',
        'publishedStatus' => 'getPublishedStatus',
        'publishedBy' => 'getPublishedBy',
        'title' => 'getTitle',
        'excerpt' => 'getExcerpt',
        'text' => 'getText',
        'categoryId' => 'getCategoryId',
        'tags' => 'getTags',
        'locale' => 'getLocale',
        'createdDate' => 'getCreatedDate',
        'lastModifiedDate' => 'getLastModifiedDate',
        'partner' => 'getPartner',
        'createdBy' => 'getCreatedBy',
        'lastModifiedBy' => 'getLastModifiedBy',
        'images' => 'getImages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const PUBLISHED_STATUS_DRAFT = 'DRAFT';
    const PUBLISHED_STATUS_PENDING = 'PENDING';
    const PUBLISHED_STATUS_PUBLISHED = 'PUBLISHED';
    const PUBLISHED_STATUS_ERROR = 'ERROR';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPublishedStatusAllowableValues()
    {
        return [
            self::PUBLISHED_STATUS_DRAFT,
            self::PUBLISHED_STATUS_PENDING,
            self::PUBLISHED_STATUS_PUBLISHED,
            self::PUBLISHED_STATUS_ERROR,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['domain'] = isset($data['domain']) ? $data['domain'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['slug'] = isset($data['slug']) ? $data['slug'] : null;
        $this->container['publishedId'] = isset($data['publishedId']) ? $data['publishedId'] : null;
        $this->container['articleId'] = isset($data['articleId']) ? $data['articleId'] : null;
        $this->container['publishedDate'] = isset($data['publishedDate']) ? $data['publishedDate'] : null;
        $this->container['publishedStatus'] = isset($data['publishedStatus']) ? $data['publishedStatus'] : null;
        $this->container['publishedBy'] = isset($data['publishedBy']) ? $data['publishedBy'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['excerpt'] = isset($data['excerpt']) ? $data['excerpt'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['categoryId'] = isset($data['categoryId']) ? $data['categoryId'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['createdDate'] = isset($data['createdDate']) ? $data['createdDate'] : null;
        $this->container['lastModifiedDate'] = isset($data['lastModifiedDate']) ? $data['lastModifiedDate'] : null;
        $this->container['partner'] = isset($data['partner']) ? $data['partner'] : null;
        $this->container['createdBy'] = isset($data['createdBy']) ? $data['createdBy'] : null;
        $this->container['lastModifiedBy'] = isset($data['lastModifiedBy']) ? $data['lastModifiedBy'] : null;
        $this->container['images'] = isset($data['images']) ? $data['images'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPublishedStatusAllowableValues();
        if (!is_null($this->container['publishedStatus']) && !in_array($this->container['publishedStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'publishedStatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['text'] === null) {
            $invalidProperties[] = "'text' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return \Sedo\SedoTMP\Content\Model\Id
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param \Sedo\SedoTMP\Content\Model\Id $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string $domain domain
     *
     * @return $this
     */
    public function setDomain($domain)
    {
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The published article url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->container['slug'];
    }

    /**
     * Sets slug
     *
     * @param string $slug Slug of the published article
     *
     * @return $this
     */
    public function setSlug($slug)
    {
        $this->container['slug'] = $slug;

        return $this;
    }

    /**
     * Gets publishedId
     *
     * @return \Sedo\SedoTMP\Content\Model\Id
     */
    public function getPublishedId()
    {
        return $this->container['publishedId'];
    }

    /**
     * Sets publishedId
     *
     * @param \Sedo\SedoTMP\Content\Model\Id $publishedId publishedId
     *
     * @return $this
     */
    public function setPublishedId($publishedId)
    {
        $this->container['publishedId'] = $publishedId;

        return $this;
    }

    /**
     * Gets articleId
     *
     * @return \Sedo\SedoTMP\Content\Model\Id
     */
    public function getArticleId()
    {
        return $this->container['articleId'];
    }

    /**
     * Sets articleId
     *
     * @param \Sedo\SedoTMP\Content\Model\Id $articleId articleId
     *
     * @return $this
     */
    public function setArticleId($articleId)
    {
        $this->container['articleId'] = $articleId;

        return $this;
    }

    /**
     * Gets publishedDate
     *
     * @return \Sedo\SedoTMP\Content\Model\\DateTime
     */
    public function getPublishedDate()
    {
        return $this->container['publishedDate'];
    }

    /**
     * Sets publishedDate
     *
     * @param \Sedo\SedoTMP\Content\Model\\DateTime $publishedDate publishedDate
     *
     * @return $this
     */
    public function setPublishedDate($publishedDate)
    {
        $this->container['publishedDate'] = $publishedDate;

        return $this;
    }

    /**
     * Gets publishedStatus
     *
     * @return string
     */
    public function getPublishedStatus()
    {
        return $this->container['publishedStatus'];
    }

    /**
     * Sets publishedStatus
     *
     * @param string $publishedStatus publishedStatus
     *
     * @return $this
     */
    public function setPublishedStatus($publishedStatus)
    {
        $allowedValues = $this->getPublishedStatusAllowableValues();
        if (!is_null($publishedStatus) && !in_array($publishedStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'publishedStatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['publishedStatus'] = $publishedStatus;

        return $this;
    }

    /**
     * Gets publishedBy
     *
     * @return \Sedo\SedoTMP\Content\Model\User
     */
    public function getPublishedBy()
    {
        return $this->container['publishedBy'];
    }

    /**
     * Sets publishedBy
     *
     * @param \Sedo\SedoTMP\Content\Model\User $publishedBy publishedBy
     *
     * @return $this
     */
    public function setPublishedBy($publishedBy)
    {
        $this->container['publishedBy'] = $publishedBy;

        return $this;
    }

    /**
     * Gets title
     *
     * @return \Sedo\SedoTMP\Content\Model\ArticleTitle
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param \Sedo\SedoTMP\Content\Model\ArticleTitle $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets excerpt
     *
     * @return \Sedo\SedoTMP\Content\Model\ArticleExcerpt
     */
    public function getExcerpt()
    {
        return $this->container['excerpt'];
    }

    /**
     * Sets excerpt
     *
     * @param \Sedo\SedoTMP\Content\Model\ArticleExcerpt $excerpt excerpt
     *
     * @return $this
     */
    public function setExcerpt($excerpt)
    {
        $this->container['excerpt'] = $excerpt;

        return $this;
    }

    /**
     * Gets text
     *
     * @return \Sedo\SedoTMP\Content\Model\ArticleText
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param \Sedo\SedoTMP\Content\Model\ArticleText $text text
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets categoryId
     *
     * @return \Sedo\SedoTMP\Content\Model\Id
     */
    public function getCategoryId()
    {
        return $this->container['categoryId'];
    }

    /**
     * Sets categoryId
     *
     * @param \Sedo\SedoTMP\Content\Model\Id $categoryId categoryId
     *
     * @return $this
     */
    public function setCategoryId($categoryId)
    {
        $this->container['categoryId'] = $categoryId;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Sedo\SedoTMP\Content\Model\ArticleTags
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Sedo\SedoTMP\Content\Model\ArticleTags $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return \Sedo\SedoTMP\Content\Model\Locale
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param \Sedo\SedoTMP\Content\Model\Locale $locale locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets createdDate
     *
     * @return \Sedo\SedoTMP\Content\Model\\DateTime
     */
    public function getCreatedDate()
    {
        return $this->container['createdDate'];
    }

    /**
     * Sets createdDate
     *
     * @param \Sedo\SedoTMP\Content\Model\\DateTime $createdDate createdDate
     *
     * @return $this
     */
    public function setCreatedDate($createdDate)
    {
        $this->container['createdDate'] = $createdDate;

        return $this;
    }

    /**
     * Gets lastModifiedDate
     *
     * @return \Sedo\SedoTMP\Content\Model\\DateTime
     */
    public function getLastModifiedDate()
    {
        return $this->container['lastModifiedDate'];
    }

    /**
     * Sets lastModifiedDate
     *
     * @param \Sedo\SedoTMP\Content\Model\\DateTime $lastModifiedDate lastModifiedDate
     *
     * @return $this
     */
    public function setLastModifiedDate($lastModifiedDate)
    {
        $this->container['lastModifiedDate'] = $lastModifiedDate;

        return $this;
    }

    /**
     * Gets partner
     *
     * @return \Sedo\SedoTMP\Content\Model\Partner
     */
    public function getPartner()
    {
        return $this->container['partner'];
    }

    /**
     * Sets partner
     *
     * @param \Sedo\SedoTMP\Content\Model\Partner $partner partner
     *
     * @return $this
     */
    public function setPartner($partner)
    {
        $this->container['partner'] = $partner;

        return $this;
    }

    /**
     * Gets createdBy
     *
     * @return \Sedo\SedoTMP\Content\Model\User
     */
    public function getCreatedBy()
    {
        return $this->container['createdBy'];
    }

    /**
     * Sets createdBy
     *
     * @param \Sedo\SedoTMP\Content\Model\User $createdBy createdBy
     *
     * @return $this
     */
    public function setCreatedBy($createdBy)
    {
        $this->container['createdBy'] = $createdBy;

        return $this;
    }

    /**
     * Gets lastModifiedBy
     *
     * @return \Sedo\SedoTMP\Content\Model\User
     */
    public function getLastModifiedBy()
    {
        return $this->container['lastModifiedBy'];
    }

    /**
     * Sets lastModifiedBy
     *
     * @param \Sedo\SedoTMP\Content\Model\User $lastModifiedBy lastModifiedBy
     *
     * @return $this
     */
    public function setLastModifiedBy($lastModifiedBy)
    {
        $this->container['lastModifiedBy'] = $lastModifiedBy;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \Sedo\SedoTMP\Content\Model\ArticleImagesList
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \Sedo\SedoTMP\Content\Model\ArticleImagesList $images images
     *
     * @return $this
     */
    public function setImages($images)
    {
        $this->container['images'] = $images;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
